// GtkSharp.Generation.EnumGen.cs - The Enumeration Generatable.
//
// Author: Mike Kestner <mkestner@speakeasy.net>
//
// Copyright (c) 2001 Mike Kestner
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of version 2 of the GNU General Public
// License as published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public
// License along with this program; if not, write to the
// Free Software Foundation, Inc., 59 Temple Place - Suite 330,
// Boston, MA 02111-1307, USA.

using System;
using System.Collections.Generic;
using System.IO;
using System.Xml;

namespace GtkSharp.Generation {

	// <enumeration name="BookmarkFileError" c:type="GBookmarkFileError" glib:error-domain="g-bookmark-file-error-quark">
	//   <doc xml:space="preserve">Error codes returned by bookmark file parsing.</doc>
	//   <member name = "invalid_uri" value="0" c:identifier="G_BOOKMARK_FILE_ERROR_INVALID_URI">
	//     <doc xml:space="preserve">URI was ill-formed</doc>
	//   </member>
	public class EnumGen : GenBase
	{
		// TODO:
		// See marshalling without casting

		class EnumMember : GenBase
		{
			public string MemberName { get; private set; }
			public string Value { get; private set; }

			bool isBitField;

			public EnumMember (bool isBitField)
			{
				this.isBitField = isBitField;
			}

			protected override void ParseElement (XmlElement ns, XmlElement elem)
			{
				base.ParseElement (ns, elem);

				MemberName = elem.GetName ();
				Value = elem.GetAttribute (Constants.Value);

				if (isBitField) {
					int value = int.Parse (Value);
					Value = string.Format ("0x{0:X}", value);
				}
			}

			public override void Generate (GenerationInfo geninfo)
			{
				geninfo.Writer.WriteLine (MemberName + " = " + Value + ",");
			}

			// These will be removed from GenBase to another layer.
			public override string MarshalType {
				get {
					throw new NotImplementedException ();
				}
			}

			public override string DefaultValue {
				get {
					throw new NotImplementedException ();
				}
			}

			public override string CallByName (string var)
			{
				throw new NotImplementedException ();
			}

			public override string FromNative (string var)
			{
				throw new NotImplementedException ();
			}

			public override bool Validate ()
			{
				return true;
			}
		}

		readonly List<EnumMember> members = new List<EnumMember> ();
		readonly bool isBitField;
		bool hasGetGType;
		string getGTypeMethod;

		public EnumGen (bool isBitField)
		{
			this.isBitField = isBitField;
		}

		protected override void ParseElement(XmlElement ns, XmlElement elem)
		{
			base.ParseElement (ns, elem);

			hasGetGType = elem.HasAttribute (Constants.GetGType);
			getGTypeMethod = elem.GetAttribute (Constants.GetGType);
		}

		protected override void ParseChildElement(XmlElement ns, XmlElement childElement)
		{
			switch (childElement.Name) {
			case Constants.Member:
				var em = new EnumMember (isBitField);
				em.Parse (ns, childElement);
				members.Add (em);
				return;
			}
			base.ParseChildElement(ns, childElement);
		}

		public override bool Validate ()
		{
			foreach (var member in members) {
				if (!member.Validate ())
					return false;
			}
			return true;
		}

		public override string DefaultValue {
			get {
				// TODO: Maybe return the first?
				return "(" + QualifiedName + ") 0";
			}
		}

		public override string MarshalType {
			get {
				// TODO: Maybe marshal it as enum?
				return "int";
			}
		}

		public override string CallByName (string var_name)
		{
			// TODO: if marshalled as enum, remove int
			return "(int) " + var_name;
		}

		public override string FromNative(string var)
		{
			return "(" + QualifiedName + ") " + var;
		}

		public override void Generate (GenerationInfo gen_info)
		{
			StreamWriter sw = gen_info.OpenStream (Name);
			gen_info.Writer = sw;

			sw.WriteLine ("namespace " + NS + " {");
			sw.WriteLine ();
			sw.WriteLine ("\tusing System;");
			sw.WriteLine ("\tusing System.Runtime.InteropServices;");
			sw.WriteLine ();

			sw.WriteLine ("#region Autogenerated code");

			if (isBitField)
				sw.WriteLine ("\t[Flags]");
			if (hasGetGType)
				sw.WriteLine ("\t[{0}]", Name);

			string access = IsInternal ? "internal" : "public";
			sw.WriteLine ("\t" + access + " enum " + Name + " {");
			sw.WriteLine ();

			foreach (var member in members) {
				sw.Write ("\t\t"); 
				member.Generate (gen_info);
			}

			sw.WriteLine ("\t}");

			if (hasGetGType) {
				AttributeHelper.Gen (sw, Name, LibraryName, getGTypeMethod);
			}

			sw.WriteLine ("#endregion");
			sw.WriteLine ("}");
			sw.Close ();
			gen_info.Writer = null;

			if (isBitField)
				Statistics.FlagsCount++;
			else
				Statistics.EnumCount++;
		}
	}
}
